// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4UtKp9aHL6lCMgBx-4xmAPNwDDp82T0I',
    appId: '1:445095481778:web:1ba0deda375f79111e54ab',
    messagingSenderId: '445095481778',
    projectId: 'moneytrack-90239',
    authDomain: 'moneytrack-90239.firebaseapp.com',
    storageBucket: 'moneytrack-90239.firebasestorage.app',
    measurementId: 'G-MEH307T1R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOMgc738_jxyKr1HmARooYE6ndr4t6uE',
    appId: '1:445095481778:android:dff642022c3a78801e54ab',
    messagingSenderId: '445095481778',
    projectId: 'moneytrack-90239',
    storageBucket: 'moneytrack-90239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-ZoagpIngr4nM8bg0K66SbsdQAKXtEk',
    appId: '1:445095481778:ios:db191ee396b02fdd1e54ab',
    messagingSenderId: '445095481778',
    projectId: 'moneytrack-90239',
    storageBucket: 'moneytrack-90239.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-ZoagpIngr4nM8bg0K66SbsdQAKXtEk',
    appId: '1:445095481778:ios:db191ee396b02fdd1e54ab',
    messagingSenderId: '445095481778',
    projectId: 'moneytrack-90239',
    storageBucket: 'moneytrack-90239.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4UtKp9aHL6lCMgBx-4xmAPNwDDp82T0I',
    appId: '1:445095481778:web:6f8c4d1c61b6bbf91e54ab',
    messagingSenderId: '445095481778',
    projectId: 'moneytrack-90239',
    authDomain: 'moneytrack-90239.firebaseapp.com',
    storageBucket: 'moneytrack-90239.firebasestorage.app',
    measurementId: 'G-ZRBM2D4YLE',
  );
}
